### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by rui-cruz** [jon4hz/deadshot#4]
![image](https://user-images.githubusercontent.com/1080374/164978582-1638a4a3-79b4-4676-885b-bef95197c5bc.png)

**Comment by rui-cruz** [comment]
It seems like a false positive?

https://answers.microsoft.com/en-us/protect/forum/all/what-to-do-about-trojanwin32wacatacbml-false/d884df80-2dba-46c9-bd8b-4e2f93c9dd3f

**Comment by rui-cruz** [comment]
Sorry for the alarm.. its working

**Comment by jon4hz** [comment]
Hey, I'm afraid that windows defender will flag the binary as a virus since I compress it with upx. If you build the binary yourself without compressing it, the defender should alarm.
